#!/bin/bash
# This script does not download the package to install it.
# This is because I assume wget/curl might not work as proxy hasn't been set.

# Working from current directory having proxyman

TARGET_DIR="$HOME/.proxyman"


# verify if this is current directory
if [[ -f "main.sh" && -f "shellrc.sh" && -f "dropbox.sh" ]]; then
    :
else
    echo "please cd to the folder containing proxyman"
    exit 1
fi

# copy the contents to ~/.proxyman/
mkdir -p $TARGET_DIR
cp * $TARGET_DIR

# add to path
mkdir -p $HOME/.local/bin
cp proxyman $HOME/.local/bin
chmod +x $HOME/.local/bin/proxyman

# add autocompletition information to .bashrc
echo "source $TARGET_DIR/proxyman_bash_completition.sh" >> $HOME/.bashrc

which proxyman &> /dev/null
if [ "$?" != 0 ]; then
    which "$HOME/.local/bin/proxyman" &> /dev/null
    if [ "$?" != 0 ]; then
        echo "Failed to install :("
        echo "You can still use it > ./main.sh set"
    else
        echo 'Instalation was successful, but ~/.local/bin/ is not in your $PATH. Things will probably work fine after your next login. In the meantime, you can source ~/.profile before running proxyman.'
    fi
else
    echo "Installed successfully."
fi
